### ISSUE TITLE
Error when using version 0.9.0 of gtp5g

### ISSUE THREAD

**Issue by louisroyer** [free5gc/go-upf#53]
1. Using the latest version of gtp5g (v0.9.0) asks the user to update `gtp5g` instead of downgrading to v0.8.10 :
```
 2024-07-08T14:49:37.282938210Z [ERRO][UPF][Main] UPF Cli Run Error: open Gtp5g: version mismatch: gtp5g version(0.9.0) should be 0.8.6 <= verion < 0.9.0 , please update it
 ```
2. There is a typo in the error message (`verion` instead of `version`)

Please update `go-upf` to allow using latest version of the driver.

**Comment by oliveiraleo** [comment]
Hello,

I've tested this setup myself recently because I updated my environment to use free5GC v3.4.2

I can confirm that both v0.9.0 and v0.9.1 UPF versions give the same "version mismatch error". However, as suggested by OP v0.8.10 works.

I've made a PR https://github.com/free5gc/go-upf/pull/55/ to fix the typo on the error message. However, perhaps, the conditional on line [no. 163](https://github.com/free5gc/go-upf/pull/55/files#diff-1385a5548b4e2bcc18c3ace78a0e5a86ac1449d48e21dd33d56b7b74f7a200b7L163) could be reworked to display a proper message (e.g. if the version is too low display "update it" otherwise display "downgrade it"). What do you guys think?

Regards, Leo.

**Comment by andy89923** [comment]
Hi @louisroyer @louisroyer ,

Thanks for reporting type & correction PR!
The **go-upf** should work with gtp5g from `v0.8.6` to `v0.8.10` version. 

> (if the version is too low display "update it" otherwise display "downgrade it"). What do you guys think?

I think it's unnecessary to differentiate the higher or lower version, so a simple display message should be fine. 

Regards, 
CTFang
